# CLI arguments
headed: False # True or False
verbose: True # True or False
parallel: False # True or False
playtest-report: True # True or False
marks: null # null or list of markers
test_dir: null # null or directory path e.g. tests/demo
test_file: null # null or file path e.g. tests/demo/test_demo.py
rerun: 1 # number of times to rerun failed tests
tracing: True # True or False